# -*- coding: utf-8 -*-
"""Datacleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f138JUvhSFOWuFiOkMuQR9juA6Zkpgh-
"""

import pandas as pd
# Load dataset
df = pd.read_csv('/content/multi_touch_attribution_dataset.csv')

print(df.isnull().sum())

print("Total duplicate rows : ",df.duplicated().sum())
df=df.drop_duplicates()

df['customer_status'] = df['customer_status'].fillna('Not Converted')

df['converted'] = df['conversion_id'].notna().astype(int)
df

df['conversion_id'] = df['conversion_id'].fillna('No_Conversion')
df['conversion_timestamp_utc'] = df['conversion_timestamp_utc'].fillna('No_Conversion')
df['customer_status'] = df['customer_status'].fillna('Not Converted')

print(df.isnull().sum())

# Save cleaned dataset
df.to_csv('/content/multi_touch_attribution_dataset_cleaned.csv', index=False)

print("Cleaned dataset saved successfully!")